/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoraatividade;

/**
 *
 * @author dti
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        lblNum1 = new javax.swing.JLabel();
        lblNum2 = new javax.swing.JLabel();
        radioButtonSoma = new javax.swing.JRadioButton();
        radioButtonSubtrair = new javax.swing.JRadioButton();
        radioButtonMultiplicar = new javax.swing.JRadioButton();
        radioButtonDividir = new javax.swing.JRadioButton();
        radioButtonResto = new javax.swing.JRadioButton();
        lblResultado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNum1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNum1.setText("Número um:");

        lblNum2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblNum2.setText("Número dois:");

        buttonGroup.add(radioButtonSoma);
        radioButtonSoma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioButtonSoma.setText("Somar");
        radioButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSomaActionPerformed(evt);
            }
        });

        buttonGroup.add(radioButtonSubtrair);
        radioButtonSubtrair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioButtonSubtrair.setText("Subtrair");
        radioButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSubtrairActionPerformed(evt);
            }
        });

        buttonGroup.add(radioButtonMultiplicar);
        radioButtonMultiplicar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioButtonMultiplicar.setText("Multiplicar");

        buttonGroup.add(radioButtonDividir);
        radioButtonDividir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioButtonDividir.setText("Dividir");

        buttonGroup.add(radioButtonResto);
        radioButtonResto.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        radioButtonResto.setText("Resto");

        lblResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblResultado.setText("Resultado:");

        btnCalcular.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        txtNum1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtNum2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNum2.setToolTipText("");

        txtResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonDividir)
                    .addComponent(radioButtonMultiplicar)
                    .addComponent(radioButtonSoma)
                    .addComponent(radioButtonSubtrair)
                    .addComponent(radioButtonResto)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNum1)
                            .addComponent(lblNum2)
                            .addComponent(lblResultado))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNum1)
                            .addComponent(txtNum2)
                            .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum1)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum2)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(radioButtonSoma)
                .addGap(18, 18, 18)
                .addComponent(radioButtonSubtrair)
                .addGap(18, 18, 18)
                .addComponent(radioButtonMultiplicar)
                .addGap(18, 18, 18)
                .addComponent(radioButtonDividir)
                .addGap(18, 18, 18)
                .addComponent(radioButtonResto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResultado)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSubtrairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonSubtrairActionPerformed

    private void radioButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSomaActionPerformed
        // TODO add your handling code here:
        String num1, num2;
        
    }//GEN-LAST:event_radioButtonSomaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        String stringNum1, stringNum2;
        float conta;
        stringNum1 = txtNum1.getText();
        stringNum2 = txtNum2.getText();
        if(radioButtonSoma.isSelected()){
            conta = Float.parseFloat(stringNum1) + Float.parseFloat(stringNum2);
            txtResultado.setText(Float.toString(conta));
        }else if(radioButtonSubtrair.isSelected()){
            conta = Float.parseFloat(stringNum1) - Float.parseFloat(stringNum2);
            txtResultado.setText(Float.toString(conta));
        }else if(radioButtonMultiplicar.isSelected()){
            conta = Float.parseFloat(stringNum1) * Float.parseFloat(stringNum2);
            txtResultado.setText(Float.toString(conta));
        }else if(radioButtonDividir.isSelected()){
            conta = Float.parseFloat(stringNum1) / Float.parseFloat(stringNum2);
            txtResultado.setText(Float.toString(conta));
        }else if(radioButtonResto.isSelected()){
            conta = Float.parseFloat(stringNum1) % Float.parseFloat(stringNum2);
            txtResultado.setText(Float.toString(conta));
        }
        lblResultado.setVisible(true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton radioButtonDividir;
    private javax.swing.JRadioButton radioButtonMultiplicar;
    private javax.swing.JRadioButton radioButtonResto;
    private javax.swing.JRadioButton radioButtonSoma;
    private javax.swing.JRadioButton radioButtonSubtrair;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
