/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.etec.comboboxcheckboxjradiobutton;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author dti
 */
public class JFrameForm extends javax.swing.JFrame {
    Integer estilo = Font.PLAIN, tamanhoFonte = 12;
    
    
    /**
     * Creates new form JFrameForm
     */
    public JFrameForm() {
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbCor = new javax.swing.JComboBox<>();
        lblTitle = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        rbtn12 = new javax.swing.JRadioButton();
        rbtn14 = new javax.swing.JRadioButton();
        rbtn16 = new javax.swing.JRadioButton();
        rbtn18 = new javax.swing.JRadioButton();
        chbNegrito = new javax.swing.JCheckBox();
        chbItalico = new javax.swing.JCheckBox();
        chbRegular = new javax.swing.JCheckBox();
        chbNegritoItalico = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbCor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Cor", "Vermelho", "Azul", "Verde", "Amarelo", "Branco", "Preto" }));
        cbCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCorActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblTitle.setText("Programa feito em Java");

        lblCor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCor.setText("Cor:");

        lblEstilo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblEstilo.setText("Estilo: ");

        lblTamanho.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTamanho.setText("Tamanho:");

        rbtn12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn12.setText("12");
        rbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn12ActionPerformed(evt);
            }
        });

        rbtn14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn14.setText("14");

        rbtn16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rbtn16.setText("16");

        rbtn18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbtn18.setText("18");

        chbNegrito.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbNegrito.setText("Negrito");
        chbNegrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbNegritoActionPerformed(evt);
            }
        });

        chbItalico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbItalico.setText("Itálico");

        chbRegular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbRegular.setText("Regular");

        chbNegritoItalico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        chbNegritoItalico.setText("Negrito Itálico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbNegritoItalico)
                            .addComponent(chbRegular)
                            .addComponent(chbNegrito)
                            .addComponent(cbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCor)
                            .addComponent(lblEstilo)
                            .addComponent(lblTamanho)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn12)
                                .addGap(36, 36, 36)
                                .addComponent(rbtn14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn16)
                                .addGap(38, 38, 38)
                                .addComponent(rbtn18)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbItalico)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblEstilo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbNegrito)
                .addGap(18, 18, 18)
                .addComponent(chbItalico)
                .addGap(21, 21, 21)
                .addComponent(chbRegular)
                .addGap(16, 16, 16)
                .addComponent(chbNegritoItalico)
                .addGap(18, 18, 18)
                .addComponent(lblTamanho)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn12)
                    .addComponent(rbtn14))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn16)
                    .addComponent(rbtn18))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCorActionPerformed
        cbCor.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                if(null != cbCor.getSelectedItem().toString())switch (cbCor.getSelectedItem().toString()) {
                    case "Sem Cor":
                        lblTitle.setForeground(Color.black);
                        break;
                    case "Vermelho":
                        lblTitle.setForeground(Color.red);
                        break;
                    case "Azul":
                        lblTitle.setForeground(Color.blue);
                        break;
                    case "Verde":
                        lblTitle.setForeground(Color.green);
                        break;
                    case "Amarelo":
                        lblTitle.setForeground(Color.yellow);
                        break;
                    case "Branco":
                        lblTitle.setForeground(Color.white);
                        break;
                    case "Preto":
                        lblTitle.setForeground(Color.black);
                        break;
                    default:
                        break;
                }
            }
        });
    }//GEN-LAST:event_cbCorActionPerformed

    private void chbNegritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbNegritoActionPerformed
        chbNegrito.addActionListener((ActionEvent e) -> {
            estilo = Font.BOLD;
            chbItalico.setSelected(false);
            chbNegritoItalico.setSelected(false);
            chbRegular.setSelected(false);
            lblTitle.setFont(new Font("", estilo, tamanhoFonte));
        });
    }//GEN-LAST:event_chbNegritoActionPerformed

    private void rbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn12ActionPerformed
        rbtn12.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                tamanhoFonte = 12;
                lblTitle.setFont(new Font("", estilo, tamanhoFonte));
            }
        });
    }//GEN-LAST:event_rbtn12ActionPerformed
    
    private void rbtn14ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        rbtn14.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                tamanhoFonte = 14;
                lblTitle.setFont(new Font("", estilo, tamanhoFonte));
            }
        });
    }
    
    private void rbtn16ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        rbtn16.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                tamanhoFonte = 16;
                lblTitle.setFont(new Font("", estilo, tamanhoFonte));
            }
        });
    }
    
    private void rbtn18ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        rbtn18.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                tamanhoFonte = 18;
                lblTitle.setFont(new Font("", estilo, tamanhoFonte));
            }
        });
    }
    
    private void chbItalicoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        chbItalico.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo = Font.ITALIC;
                chbRegular.setSelected(false);
                chbNegritoItalico.setSelected(false);
                chbNegrito.setSelected(false);
                lblTitle.setFont(new Font("", estilo, tamanhoFonte));
            }
        });
    }
    
    private void chbRegularActionPerformed(java.awt.event.ActionEvent evt) {                                           
        chbRegular.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo = Font.PLAIN;
                chbItalico.setSelected(false);
                chbNegritoItalico.setSelected(false);
                chbNegrito.setSelected(false);
                lblTitle.setFont(new Font("", estilo, 24));
            }
        });
    }
    
    private void chbNegritoItalicoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        chbNegritoItalico.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                estilo = Font.BOLD + Font.ITALIC;
                chbItalico.setSelected(false);
                chbRegular.setSelected(false);
                chbNegrito.setSelected(false);
                lblTitle.setFont(new Font("", estilo, 24));
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCor;
    private javax.swing.JCheckBox chbItalico;
    private javax.swing.JCheckBox chbNegrito;
    private javax.swing.JCheckBox chbNegritoItalico;
    private javax.swing.JCheckBox chbRegular;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtn12;
    private javax.swing.JRadioButton rbtn14;
    private javax.swing.JRadioButton rbtn16;
    private javax.swing.JRadioButton rbtn18;
    // End of variables declaration//GEN-END:variables
}
